nth term and sum of all in arithemetic sequence
mathincubator/mathlib pull request #10
Opened 2021-09-18 16:14 UTC by andrewhe01

2021-09-18 17:49 UTC, kylerluo reviewed
Andrew, you have several issues with your code.

1. You have checked in your test code. Follow Carole's code format.
2. There are no comments regarding your code. Very difficult for others to understand what you're trying to do. Explain your code via comments, please.
3. If "n" is out of the index range, you've returned None. The user will have no idea why the code is not working. You should return an error instead of None.

2021-09-18 17:49 UTC, kylerluo requested changes
Andrew, you have several issues with your code.

1. You have checked in your test code. Follow Carole's code format.
2. If "n" is out of the index range, you've returned None. The user will have no idea why the code is not working. You should return an error instead of None.

2021-10-02 18:21 UTC, kylerluo requested changes
You still have your test code at the bottom.

You also have so many unnecessary new lines...

2021-10-16 15:45 UTC, warrior2278 approved these changes

2021-10-16 15:45 UTC, merged